apiVersion: v1
kind: Service
metadata:
  name: web-app-service
  namespace: web-app
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-protocol: "http"
spec:
  type: LoadBalancer
  selector:
    app: web-app
  ports:
    - protocol: TCP
      port: 80  # Exposes port 80
      targetPort: 3000  # app is on port 3000
